### ISSUE TITLE
github action

### ISSUE THREAD

**Issue by jorgepz** [mihdicaballero/LaTeX-Projects#1]
Sería awesome configurar el github action. Creo que uno adecuado sería este https://github.com/xu-cheng/latex-action

**Comment by mihdicaballero** [comment]
Sip, ya lo tengo iniciado pero no está funcionando todavía :(

Tengo esto por ahora:

```name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Simple and elegant report/Simple_report.tex
```
Este es el archivo [Link](https://github.com/mihdicaballero/LaTeX-Projects/blob/main/.github/workflows/LaTeX-Action.yml)

**Comment by jorgepz** [comment]
sí... ahi lo ví. hice un intento en #2

**Comment by jorgepz** [comment]
el detalle de la salida lo ves acá https://github.com/mihdicaballero/LaTeX-Projects/runs/5556310027?check_suite_focus=true#step:4:20

**Comment by jorgepz** [comment]
vi el error me parece que hay q cambiar el working directory... de todas formas para probar el CI sugiero poner un ejemplo minimal en la raiz del repo... de después progresivamente moverlo y después agregar otro archivo con input

**Comment by mihdicaballero** [comment]
Sep, vamos de a poco. Venga tío.

**Comment by jorgepz** [comment]
sugiero hacer dos compilaciones independientes... por un lado el main y por otro el simple report
además sugiero quitar los espacios de los nombres de las carpetas...
además se puede poner _artifacts_ que hace que se suba el pdf después de compilar

**Comment by mihdicaballero** [comment]
Encontré esto que muestra como hacer un release con el PDF que se compiló.
[https://dev.to/mrturkmen/latex-with-github-actions-4580](https://dev.to/mrturkmen/latex-with-github-actions-4580)

**Comment by jorgepz** [comment]
impecable, no veo donde queda subido.
agregué un badge con el status del CI

**Comment by mihdicaballero** [comment]
No es changa esto de que se subá. Probé con algo más que encontré pero no hubo caso. Además de que una cosa es que suba el ZIp y otra es que suba el PDF. De última puede subirse con un commit el PDF y el action simplemente revisa que se siga compilando bien.

**Comment by jorgepz** [comment]
hice este repo para hacer pruebas https://github.com/LaTeXUy/pruebas-LaTeX-CI
